Create addAttrs() method
firstandthird/domassist pull request #20
Opened 2017-02-01 09:19 UTC by mturnwall

2017-02-01 18:13 UTC, jgallen23 requested changes

2017-02-01 18:13 UTC, jgallen23 commented on lib/addAttrs.js
> +    selector.forEach((item) => addAttrs(item, attrs));
you need a return after this

2017-02-01 18:13 UTC, jgallen23 commented on lib/addAttrs.js
> +  if (Array.isArray(selector)) {
you also don't have a test for this

2017-02-03 07:11 UTC, mturnwall commented on lib/addAttrs.js
> +  if (Array.isArray(selector)) {
I added a test to send an array to the method.
https://github.com/firstandthird/domassist/pull/20/files#diff-6857e5b1a304c14415231f3cf322e5dcR60

2017-02-03 14:54 UTC, merged