Update add/remove classes to accept array of elements and classes
firstandthird/domassist pull request #24
Opened 2017-02-02 08:13 UTC by mturnwall

2017-02-02 21:26 UTC, jgallen23 requested changes

2017-02-02 21:26 UTC, jgallen23 commented on lib/addClass.js
> +      if (Array.isArray(cls)) {
just convert cls to always be a class if its not, saves you a check

2017-02-02 21:26 UTC, jgallen23 commented on lib/removeClass.js
> +      if (Array.isArray(cls)) {
same here

2017-02-03 06:58 UTC, mturnwall commented
I wasn't exactly sure what you meant by converting `cls` to always be a class. So just always convert `cls` to be an array instead.

`const clsArray = [].concat(cls);`

2017-02-03 14:56 UTC, jgallen23 commented
You should do the conversion higher up. Inefficient right now to do it inside the loop

2017-02-03 14:56 UTC, jgallen23 commented
And need merge

2017-02-03 20:01 UTC, merged